name: Generate Image with Hugging Face API

on:
  workflow_dispatch: # Allows you to manually trigger the action from the GitHub Actions interface

jobs:
  generate_image:
    runs-on: ubuntu-22.04  # Specify ubuntu-22.04 for now

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow

    - name: Run image generation script
      run: |
        python Images/generate_image.py

    - name: Upload generated image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-image
        path: Images/generated_image_16x9.png
        
