name: Generate Images from Prompts

on:
  workflow_dispatch:
    inputs:
      prompts:
        description: "Semicolon-separated prompts to generate images"
        required: true
        default: ""

permissions:
  contents: write  # Required to push changes to the repository

jobs:
  generate_images:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow

    - name: Run image generation script
      env:
        HG_TOKEN: ${{ secrets.HG_TOKEN }}
        PROMPTS: ${{ github.event.inputs.prompts }}
      run: |
        python Images/image_upload.py

    - name: Create Images directory if it doesn't exist
      run: |
        mkdir -p Images

    - name: Set up Git user
      run: |
        git config --global user.name "ansentase"
        git config --global user.email "samomsan7@gmail.com"

    - name: Commit and push generated images
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Use secret for authentication
      run: |-
        git add Images/*.png
        timestamp=$(date -u)
        git commit -m "Generated images: ${timestamp}" || exit 0
        git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git
        git push
